package com.mahait.gov.in.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

import lombok.Data;


@Data
@Entity
@Table(name = "frm_sub_postid_mpg") 
public class SubjectPostMpg {
	
	 @Id
	    @GeneratedValue(strategy = GenerationType.IDENTITY) // Assuming ID is generated by the database
	    @Column(name = "POST_ID") // Maps to column name "POST_ID"
	    private Long postId;

	    @Column(name = "SUBJECT_NAME", nullable = false, length = 100) // Maps to column name "SUBJECT_NAME"
	    private String subjectName;

}
